"""added DisplaySlot

Revision ID: 1459f225a5b7
Revises: 325d3d664417
Create Date: 2026-05-10 22:28:08.262422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1459f225a5b7'
down_revision = '325d3d664417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('display_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('skin_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('slot_index BETWEEN 0 AND 3', name='ck_slot_index_range'),
    sa.ForeignKeyConstraint(['skin_id'], ['skins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'slot_index', name='uq_user_slot')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('display_slot')
    # ### end Alembic commands ###
