"""empty message

Revision ID: 16ac75edd085
Revises: 61651c667810
Create Date: 2026-05-11 01:37:19.294366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16ac75edd085'
down_revision = '61651c667810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_display')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_display',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('slot', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skin_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['skin_id'], ['skins.id'], name=op.f('user_display_skin_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_display_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_display_pkey'))
    )
    # ### end Alembic commands ###
