"""empty message

Revision ID: 20be2d69ebf8
Revises: 
Create Date: 2026-05-09 02:40:15.206866

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20be2d69ebf8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_date', sa.DateTime(), nullable=False))
        batch_op.drop_column('fuckthisshit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuckthisshit', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('release_date')

    # ### end Alembic commands ###
