"""empty message

Revision ID: 2e658b2bf3b0
Revises: 75b1bbe732c7
Create Date: 2026-05-11 21:17:28.340967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e658b2bf3b0'
down_revision = '75b1bbe732c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_owned', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_collection', schema=None) as batch_op:
        batch_op.drop_column('is_owned')

    # ### end Alembic commands ###
