"""empty message

Revision ID: 3376ac877058
Revises: 4ade2b7afd29
Create Date: 2026-05-11 20:47:43.276740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3376ac877058'
down_revision = '4ade2b7afd29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gold')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gold', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
