"""empty message

Revision ID: 4ade2b7afd29
Revises: 16ac75edd085
Create Date: 2026-05-11 20:44:50.276956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ade2b7afd29'
down_revision = '16ac75edd085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('essence', sa.Integer(), nullable=True))
        batch_op.drop_column('currency')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('essence')

    # ### end Alembic commands ###
