"""add displayslot

Revision ID: 61651c667810
Revises: eaf684669c3b
Create Date: 2026-05-11 00:42:07.590256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61651c667810'
down_revision = 'eaf684669c3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_display',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('skin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skin_id'], ['skins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_display')
    # ### end Alembic commands ###
