"""add duplicate count, unique_constraint for UserCollection, bug_fixes

Revision ID: 9be301441017
Revises: 20be2d69ebf8
Create Date: 2026-05-09 19:07:08.204261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be301441017'
down_revision = '20be2d69ebf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duplicate_count', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('uq_user_skin', ['user_id', 'skin_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_collection', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_skin', type_='unique')
        batch_op.drop_column('duplicate_count')

    # ### end Alembic commands ###
