"""empty message

Revision ID: a0bfd5cc62d8
Revises: c7c52cce4453
Create Date: 2026-05-13 22:11:05.246808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0bfd5cc62d8'
down_revision = 'c7c52cce4453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_date', sa.Date(), nullable=True))
        batch_op.alter_column('pull_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.create_index(batch_op.f('ix_users_join_date'), ['join_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_join_date'))
        batch_op.alter_column('pull_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('join_date')

    # ### end Alembic commands ###
