"""empty message

Revision ID: a6e05717c1ab
Revises: c5e43e0d1417
Create Date: 2026-05-11 20:48:58.478850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e05717c1ab'
down_revision = 'c5e43e0d1417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gold')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gold', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
