"""add index to obtained_at for fast loading

Revision ID: c7c52cce4453
Revises: c81be8760f99
Create Date: 2026-05-13 01:05:42.642185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c52cce4453'
down_revision = 'c81be8760f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_collection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_collection_obtained_at'), ['obtained_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_collection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_collection_obtained_at'))

    # ### end Alembic commands ###
